[program:rabbitmq-order-notifications]
process_name=%(program_name)s
command=php /var/webroot/sites/ttter.syvak.com/app/artisan rabbitmq:consume:order-notifications
numprocs=1
autostart=true
autorestart=true
startsecs=10
startretries=10
redirect_stderr=false
stdout_logfile=/var/log/php-fpm/rabbitmq-order-notifications.log
stderr_logfile=/var/log/php-fpm/rabbitmq-order-notifications-error.log
stopsignal=QUIT
stopwaitsecs=200
