# Requires a password to access Redis
requirepass "pT6%njY0&ceK-wO5+yzU"

protected-mode yes
loglevel debug
logfile "/var/log/redis.log"
databases 1

# Persistence: AOF (Append Only File)
appendonly yes

# Persistence: RDB snapshot (every 60 sec if 1000+ changes)
save 60 1000

# ACL (Access Control Lists)
# Create user "my_user" with password "my_user_password".
user "cU8xbQ5goM" on >"wC2+nj4-sxU8_kJ9zN5%" ~* &* +@all